if __name__ == "__main__":
    print("       A")
    print("      B B")
    print("     C   C")
    print("    D     D")
    print("   E       E")
    print("    D     D")
    print("     C   C")
    print("      B B")
    print("       A")
